apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deepdive
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-deepdive
  template:
    metadata:
      labels:
        app: devops-deepdive
    spec:
      containers:
      - name: devops-deepdive
        image: dopestudy/deepdive_jjw:latest
        ports:
        - containerPort: 3000