apiVersion: v1
kind: Service
metadata:
  name: devops-deepdive
  namespace: default
spec:
  selector:
    app: devops-deepdive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer